#!/bin/busybox sh

# Install symlinks to all busybox applets first.
/bin/busybox mkdir -p /usr/sbin /usr/bin /sbin /bin
/bin/busybox --install -s

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

#disable kernel base aslr
#echo 0 > /proc/sys/kernel/randomize_va_space

# Do your stuff here.
echo "This script just runs fuzzcan"
#exec /bin/fuzzcan -r
exec sh

# Mount the root filesystem.
#mount -o ro /dev/sda1 /mnt/root

# Clean up.
umount /proc
umount /sys

# Boot the real thing.
#exec switch_root /mnt/root /sbin/init

